### ISSUE TITLE
Inconsistent usage of var(--xxx) [Feature Request]

### ISSUE THREAD

**Issue by GwynethLlewelyn** [EhanAhamed/nord-bootstrap#6]
Hi again!

I'm _not_ a SASS user (or, for that matter, a user of any of the zillions of frameworks to generate CSS...), so I'm not sure if my 'feature request' makes any sense or not. Please ignore it if it doesn't :smile:

Instead, I still think that the best tool for writing consistent CSS is a good search & replace function supporting regular expressions :smiley: But don't quote me, I'm just old-school and clearly out of touch with contemporary UI/UX design practices...

However, I'm most definitely a die-hard Nord fan — even before Dark Mode was as popular as it is these days. Actually, my first Nord-themed project was a _light_ version, which I _manually_ changed from scratch, a couple of years ago; but it takes far too much time to properly do it again from scratch for a _dark_ theme, thus my interest in this project.

So, I grabbed this project's _pre-built_ CSS and experimented with it for a bit in a 'new' project I'm doing which just requires quick & dirty CSS for a basic Bootstrap theme. Since I don't really need a lot of high-end things, and since the CSS from this project seems to work only under Bootstrap 4, I was more than happy to use Bootstrap 4. It's more than enough for my needs!

While browsing through the CSS, however, I started to find a few inconsistencies. Let me start with a good example: `font-family`. I'm used to having a thorough `:root` with lots of `--xxx` definitions, and I was happy to see that there were already two presets, one for a sans-serif font, another for a monospace font. Cool! 😎 

However, there is nowhere in the rest of the CSS where `var(--font-family-sans-serif)` or `var(--font-family-monospace)` is used. Weird. The multiple definitions are, however, consistent with those two variables; they have been copy & paste'd correctly (I presume via the SASS building tools...?) for the whole CSS file.

'Fixing' this took a simple search & replace.

Alas... I also noticed that the colours defined on `:root` seemed to be fine in general (according to the [Nord guidelines for UI/UX design](https://www.nordtheme.com/docs/colors-and-palettes)). But... once again, these variables are _not_ being used in the CSS — at all!

While, _in general_, most colours were correctly copied & pasted, and were consistent not only with the Nord guidelines, but also with the Bootstrap nomenclature, the problem is that, in this case, it was _not_ a matter of doing a search & replace. First, because there were a _few_ mistakes (very few, in fact). Some cases were also not quite obvious: for instance, should the <abbr title="#81a1c1">colour for the 'info' group</abbr> (text, borders, fills, boxes, tables...) be the same colour as the '--cyan' colour? Does that actually make sense? (I would say it does) Then should _all_ instances of this colour be turned into `var(--info)` or to `var(--cyan)`? Is `var(--cyan)` actually being used _outside_ of an 'info' context? (it is)

Adjusting this required manual replacement, which took a long time... and errors might have popped in, of course. That's the whole point of using `var(--xxx)`, after all!

Another issue is more complicated to deal with: non-standard colours that are not part of the Nord palette. This happens sometimes with some highlights/hover colours for info/warning/error boxes or tables or text. The original Bootstrap palette seems to have favoured a much larger palette than the 16-colour Nord palette. But there can be a few adaptations and still stick to the Nord palette while providing some subtle highlighting. I've attempted to do that consistently, but, again, there might be some issues here and there (I didn't check _everything_!).

Finally, I've also noticed that `:root` defines things like `--breakpoint-xs` etc. This makes a _lot_ of sense, to make sure that all breakpoints are correctly set to the same values — and if you need to change them, it's far easier to change them in `:root`. Sadly, though, the variables for the breakpoints are _not_ used _anywhere_. While most of them can safely be searched & replaced, there are other cases where it's much more ambiguous to know what was the intent — actually signaling a measurement that should be aligned with a particular breakpoint, or was it mere coincidence? Such nuances escape my understanding of the Bootstrap CSS; all I could do was mechanically change all values to the best of my knowledge and ability.

That being said, I'm attaching 'my' version of the CSS, edited to reflect most of the issues I noticed. Since I did _not_ use SASS or any such similar CSS assembling tool, I can only present the 'final' result, in the hope that it serves some purpose.

Possibly, though, the trouble of backporting this to the existing SASS scaffolding is not worth the trouble — especially if it's being rewritten to support Bootstrap 5! 😁 

https://gist.github.com/GwynethLlewelyn/b082e7eadca6a9ed58d9c9715e1efd2c

**Comment by SaberToothed-Dev** [comment]
Hai there, @GwynethLlewelyn! 👋 

This project currently uses a horribly made visual bootstrap theming tool that generates css/scss without any usage of proper css or scss conventions.

> Possibly, though, the trouble of backporting this to the existing SASS scaffolding is not worth the trouble — especially if it's being rewritten to support Bootstrap 5! 😁

As you pointed out, there's no point in fixing this issue right now, since this project is currently being re-written to no longer use the visual theming tool that caused these issues, thus, it would be better to wait until its rewritten instead of fixing these issues now, since rewriting the project will also fix these issues.

**Comment by GwynethLlewelyn** [comment]
Oh, no worries — see, now I've taken my own time to acknowledge your message :)

I'll be awaiting the (hopefully upcoming!) rewriting of the code :)

**Comment by EhanAhamed** [comment]
Hi Again @GwynethLlewelyn! 

I've finished completly rewriting the repository's structure so that it uses the build tools used in bootstrap.

The CSS files should now look identical to bootstrap's files except for the colors and a few minor differences, in addition to that theres also now a rtl version of the css!

The CSS files still don't use variables in every instance, but that is the same in bootstrap and is the expected output, since now they use `var(--variable)` wherever possible, unlike before when it was haphazardly inconsistent for no reason.
